spring:
  datasource:
    url: jdbc:mysql://192.168.12.105:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    db-name: guns
    filters: log4j,wall,mergeStat